CREATE DATABASE gittub;
USE gittub;

SET @@global.auto_increment_increment = 1;

CREATE TABLE IF NOT EXISTS IMAGES(
`IID` INT NOT NULL AUTO_INCREMENT,
`URL` VARCHAR(1000) DEFAULT NULL,
PRIMARY KEY(`IID`)
)ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE TABLE IF NOT EXISTS BLOCKS(
`BID` INT NOT NULL AUTO_INCREMENT,
`BLOCKNAME` VARCHAR(50) DEFAULT NULL,
`LOGO` INT NOT NULL,
CONSTRAINT FOREIGN KEY(`LOGO`) REFERENCES IMAGES(`IID`),
PRIMARY KEY(`BID`)
)ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE TABLE IF NOT EXISTS USER(
`UID` INT NOT NULL AUTO_INCREMENT,
`USERNAME` VARCHAR(50) DEFAULT '未设置昵称！！',
`PASSWORD` VARCHAR(50) NOT NULL,
`EMAIL` VARCHAR(50) NOT NULL,
`HEAD_PORTRAIT` INT DEFAULT 1,
`ADMIN_PERMISSION` TINYINT(1) DEFAULT 0,
`STATUS` VARCHAR(5) DEFAULT 'N',
`CODE` VARCHAR(10) DEFAULT NULL,
`COMMENT` VARCHAR(50) DEFAULT '这个人很懒，什么都没有写',
CONSTRAINT FOREIGN KEY(`HEAD_PORTRAIT`) REFERENCES IMAGES(`IID`),
PRIMARY KEY(`UID`)
)ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE TABLE IF NOT EXISTS POSTS(
`PID` INT NOT NULL AUTO_INCREMENT,
`UID` INT NOT NULL,
`BID` INT NOT NULL,
`TITLE` VARCHAR(100) NOT NULL,
`ABSTRACT` VARCHAR(1000) NOT NULL,
`CONTENT` TEXT DEFAULT NULL,
`TIME` DATETIME DEFAULT '9999-12-31 23:59:59',
`SHOW` TINYINT(1) DEFAULT 1,
`VIEW` INT DEFAULT 0,
`LIKED` INT DEFAULT 0,
CONSTRAINT FOREIGN KEY(`UID`) REFERENCES USER(`UID`),
CONSTRAINT FOREIGN KEY(`BID`) REFERENCES BLOCKS(`BID`),
CONSTRAINT FOREIGN KEY(`IMAGE`) REFERENCES IMAGES(`IID`),
PRIMARY KEY(`PID`)
)ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE TABLE IF NOT EXISTS REPLY(
`REID` INT NOT NULL AUTO_INCREMENT,
`UID` INT NOT NULL,
`PID` INT NOT NULL,
`CONTENT` TEXT DEFAULT NULL,
`TIME` DATETIME DEFAULT '9999-12-31 23:59:59',
`SHOW` TINYINT(1) DEFAULT 1,
CONSTRAINT FOREIGN KEY(`UID`) REFERENCES USER(`UID`),
CONSTRAINT FOREIGN KEY(`PID`) REFERENCES POSTS(`PID`),
PRIMARY KEY(`REID`)
)ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE TABLE IF NOT EXISTS FAVORITE_UID(
`FUID` INT NOT NULL AUTO_INCREMENT,
`UID` INT NOT NULL,
`LIKEDUID` INT NOT NULL,
`TIME` DATETIME DEFAULT '9999-12-31 23:59:59',
CONSTRAINT FOREIGN KEY(`UID`) REFERENCES USER(`UID`),
CONSTRAINT FOREIGN KEY(`LIKEDUID`) REFERENCES USER(`UID`),
PRIMARY KEY(`FUID`)
)ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE TABLE IF NOT EXISTS FAVORITE_PID(
`FPID` INT NOT NULL AUTO_INCREMENT,
`UID` INT NOT NULL,
`PID` INT NOT NULL,
`TIME` DATETIME DEFAULT '9999-12-31 23:59:59',
CONSTRAINT FOREIGN KEY(`UID`) REFERENCES USER(`UID`),
CONSTRAINT FOREIGN KEY(`PID`) REFERENCES POSTS(`PID`),
PRIMARY KEY(`FPID`)
)ENGINE=INNODB DEFAULT CHARSET=UTF8;

INSERT INTO IMAGES (`URL`) VALUES
('https://pic3.zhimg.com/50/v2-e2361d82ce7465808260f87bed4a32d0_qhd.jpg');
('http://qdnhdgyix.bkt.clouddn.com/111')
('http://qdnhdgyix.bkt.clouddn.com/222')
('http://qdnhdgyix.bkt.clouddn.com/333')
('http://qdnhdgyix.bkt.clouddn.com/444')

INSERT INTO BLOCKS (`BLOCKNAME`, `LOGO`) VALUES
('美食', 1),
('书籍', 1),
('体育', 1),
('财经', 1),
('政治', 1),
('学习', 1);

INSERT INTO USER (`USERNAME`, `PASSWORD`, `EMAIL`, `HEAD_PORTRAIT`, `ADMIN_PERMISSION`, `STATUS`, `CODE`, `COMMENT`) VALUES
('狗管理一号', SHA1('12345678'), '1146186018@qq.com', 2, 1, 'Y', 'QWER', '虽千万人吾亦往矣'),
('狗管理二号', SHA1('87654321'), '814384981@qq.com', 3, 1, 'Y', 'tyui', '海不邀我自来也！！！'),
('贾丁', SHA1('qwertyui'), '814384981@qq.com', 4, 0, 'Y', '1284', '别和我闹了'),
('毕展语', SHA1('11111111'), '814384981@qq.com', 1, 0, 'Y', '1k4g', '让我们一起大喊——666！'),
('李泽宇', SHA1('12345679'), '814384981@qq.com', 1, 0, 'N', 's8cr', '海上升明月');

INSERT INTO POSTS (`UID`, `BID`, `TITLE`, `ABSTRACT`, `CONTENT`, `IMAGE`, `TIME`, `SHOW`, `VIEW`, `LIKED`)VALUES
(1, 1, '给大家介绍学校周边好吃的', '学校 周边 美食', '想来想去也不知道今天中午吃什么，于是我灵机一动，不如今天大家中午吃榴莲螺蛳粉吧！', NULL, '2020-7-16 14:05:20', 1, 20, 3),
(2, 1, '今天晚上吃KFC', '星期四 开封菜 优惠', '今天晚上大家一起去吃开封菜好啦！！今天是疯狂星期四哦~', 2, '2020-7-16 15:05:20', 1, 25),
(3, 1, '今天吃夜宵吗', '夜宵 饿死了', '没赶上前两波，只能吃夜宵了……', 1, '2020-7-16 20:05:20', 0, 14),
(4, 1, '今天吃夜宵吗 写错了', '夜宵 饿死了', '没赶上前两波，只能吃夜宵了……', NULL, '2020-7-16 20:05:20', 0, 0);

INSERT INTO REPLY (`UID`, `PID`, `CONTENT`, `TIME`, `SHOW`) VALUES
(1, 2, '好诶！我们一起去吧！', '2020-7-16 16:11:20', 1),
(2, 1, '？？？我不吃', '2020-7-16 15:23:20', 1),
(1, 1, '？人间美味还有人不吃', '2020-7-16 19:11:20', 0);

INSERT INTO FAVORITE_UID (`UID`, `LIKEDUID`, `TIME`) VALUES
(1, 2, '2020-7-14 16:11:20'),
(2, 1, '2020-7-13 15:51:20');

INSERT INTO FAVORITE_PID (`UID`, `PID`, `TIME`) VALUES
(1, 1, '2020-7-17 16:11:20'),
(1, 2, '2020-7-17 15:51:20'),
(2, 1, '2020-7-17 15:51:20');